# Generated by Django 4.2.1 on 2023-06-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_employee_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[(1, 'Junior'), (2, 'Middle'), (3, 'Senior')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
