# Generated by Django 4.2.1 on 2023-06-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_department_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('jur', 'Junior'), ('mid', 'Middle'), ('sen', 'Senior')], max_length=10),
        ),
    ]
