# Generated by Django 4.2.2 on 2023-06-22 20:19

import django.core.validators
from django.db import migrations, models
import musicapp.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), musicapp.web.models.validate_string_alphanumerical]),
        ),
    ]
