# Generated by Django 4.2.2 on 2023-06-24 06:19

import django.core.validators
from django.db import migrations, models
import fruitipedia.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), fruitipedia.web.models.first_char_is_letter]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1), fruitipedia.web.models.first_char_is_letter]),
        ),
    ]
