# Generated by Django 4.2.1 on 2023-06-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_employee_options_department_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'PROJECTS'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='birth_date',
            new_name='start_date',
        ),
    ]
